### ISSUE TITLE
Support for NewTypes

### ISSUE THREAD

**Issue by adsharma** [yukinarit/pyserde#109]
The attached example fails to serialize:

```
from dataclasses import dataclass
from serde import deserialize, serialize
from typing import NewType
from serde.msgpack import from_msgpack, to_msgpack

UserId = NewType("UserId", int)

@deserialize
@serialize
@dataclass
class Test:
    id: UserId


t = Test(id=UserId(10))
print(to_msgpack(t))
```

**Comment by yukinarit** [comment]
OK, this is how to extract underlying type from NewType.

```python
print(Int.__supertype__)
```

* https://github.com/python/cpython/blob/master/Lib/typing.py#L2222
* Some other experiments: https://wandbox.org/permlink/AYGxQWjyYHbbkM7v

**Comment by yukinarit** [comment]
Hi, @adsharma  

I added NewType support for primitives. Could you  check?

**Comment by adsharma** [comment]
Works great! Thanks for fixing.

**Comment by yukinarit** [comment]
Hi @adsharma 

Just wanted to let you know v0.3.2 is pushed to PyPI! 🙂
