### ISSUE TITLE
Feature request: Custom (De)serialization functions for dates

### ISSUE THREAD

**Issue by mtnakayama** [yukinarit/pyserde#132]
Some objects have multiple ways they can be serialized. When reading JSON files generated by other programs, dates are not always compatible with `datetime.fromisoformat`. Users should be able to specify how to serialize and deserialize this data on a per-field basis.

This could either be implemented specifically for dates or more generically for other data. For dates, user could specify a string to be used in strftime/strptime.

```py
@deserialize
@serialize
@dataclass
class Foo:
    some_date: datetime.datetime = field(metadata={'serde_date': '%d/%m/%y'})
```

Or in a more generic case where users can supply custom serialization and deserialization functions. 

```py
DATE_FMT = '%d/%m/%y'

@deserialize
@serialize
@dataclass
class Foo:
    some_date: datetime.datetime = field(metadata={
        'serde_serialize': lambda x: x.strftime(DATE_FMT),
        'serde_deserialize': lambda x: datetime.strptime(x, DATE_FMT)
    })
```

**Comment by yukinarit** [comment]
Hi @mtnakayama  
I agree to your idea both `serde_date` and `serde_serialize`/`serde_deserialize`! 

I have implemented `serde_serialize`/`serde_deserialize` first because it's more generic! could you please check?
I still need to ponder API design and write more tests though.

**Comment by yukinarit** [comment]
Hi @mtnakayama  

The new pyserde 0.4.0 was just pushed to PyPI! pyserde 0.4.0 supports class/field level custom (de)serializer. Please check README or [example](https://github.com/yukinarit/pyserde/blob/master/examples/custom_field_serializer.py) for more information.

Thank you!
