### ISSUE TITLE
Canonical serialization

### ISSUE THREAD

**Issue by adsharma** [yukinarit/pyserde#143]
This was discussed here back in 2016 https://github.com/msgpack/msgpack/issues/215

Does pyserde have a repeatable serialization that could be fed to hashlib?

```
import hashlib

from datetime import datetime
from typing import Optional
from dataclasses import dataclass
from serde import serialize
from serde.msgpack import to_msgpack

@serialize
@dataclass
class Entry:
    feed_url: str
    id: str
    updated: Optional[datetime] = None

e = []
for i in range(3):
    entry = Entry('feed one', 'id', datetime(i+1, i+1, i+1))
    e.append(entry)

for i in range(3):
    for j in range(3):
        print(hashlib.sha256(to_msgpack(e[j])).hexdigest())
```

seems repeatable. But I haven't tested it across platforms.

Also see:

https://death.andgravity.com/stable-hashing where json was used
https://github.com/yuan-xy/canoser-python where dataclasses could be used, but are not.

**Comment by yukinarit** [comment]
Hi @adsharma  

> Does pyserde have a repeatable serialization that could be fed to hashlib? 

Does it mean pyserde returns the same dict/tuple inside `to_msgpack`? If that's the case, I would say YES although I haven't tested officially in all the platforms and python versions. 

A few thoughts on [msgpack-python's issue](https://github.com/msgpack/msgpack/issues/215) are 
* dict is unordered in Python<=3.6
* [@ludocode](https://github.com/msgpack/msgpack/issues/215#issuecomment-242991200) mentioned the many types in msgpack is not stable across the implementations and different programming languages. Please make sure the program uses only 1 msg pack implementation. Or perhaps better to use JSON instead? 🤔 

Another thought on this blog https://death.andgravity.com/stable-hashing is pyserde covers most of the features needed for this use case 👍 
* pyserde provides serialization of `datetime`
* pysrede provides `serde_skip` to skip serializing/deserializing a field

**Comment by adsharma** [comment]
* In my modeling of network messages, there is rarely a dict in the message. Even if there is, it could be modeled as two vectors.
* Re: representing the number -20 in many different ways, we just need to use pyserde as a reference implementation and say, -20 is to be represented as EC. Works for me :)
* Yes, like `serde_skip` better.
* JSON: msgpack is more compact and probably faster to parse.

**Comment by yukinarit** [comment]
sounds good!

**Comment by yukinarit** [comment]
@adsharma Is it ok to close this issue?

**Comment by adsharma** [comment]
Yes, Thanks for the feedback.
