### ISSUE TITLE
Add example for serializing Numpy data

### ISSUE THREAD

**Issue by Besler** [yukinarit/pyserde#145]
After playing for some time, it would be nice to have an example for serialization with a Numpy type. I have given a starting example below. The essence is:
- Specify type annotation with `numpy.typing`
- Use `__post_init__` to convert a `List[float]` to the annotated type
- When (de)serializing, convert to a serializable object type

**examply.py**
```python
from dataclasses import dataclass, field
from serde import serialize, deserialize
from serde.json import from_json, to_json
import numpy as np
import numpy.typing as npt


@serialize
@deserialize
@dataclass
class Foo:
    a: npt.NDArray[np.float64] = field(
        metadata={
            'serde_serializer': lambda x: x.tolist(),
            'serde_deserializer': lambda x: np.array(x, dtype=np.float64),
        }
    )

    def __post_init__(self):
        self.a = np.array(self.a, dtype=np.float64)

# Create using a list
f = Foo(a=[1., 0.])

# Check type of "f.a"
print(type(f.a))

# Serialize
print(to_json(f))

# Deserialize
s = '{"a": [1.0, 2.0]}'
print(from_json(Foo, s))
```

**python example.py**
```bash
<class 'numpy.ndarray'>
{"a": [1.0, 0.0]}
Foo(a=array([1., 2.]))
```

**Pit falls**
Ideally, `numpy.ndarray` could serialize itself. If one removes the `serde_*` metadata, the following error is found:
```bash
serde.compat.SerdeError: Unsupported type: ndarray
```
It is very nice to include the numpy type in the dataclass instead of `List[float]` because then all the methods can be called directly. (e.g. `f.a.max()`). Maybe there is a better solution to avoid all the extra field methods?

Any feedback would be appreciated and whether this is a worthwhile contribution.

**Comment by Besler** [comment]
Adding an example for numpy array of type complex.

**complex_number.py**
```python
from dataclasses import dataclass, field
from serde import serialize, deserialize
from serde.json import from_json, to_json
import numpy as np
import numpy.typing as npt


@serialize
@deserialize
@dataclass
class FooComplex:
    a: npt.NDArray[np.cdouble] = field(
        metadata={
            'serde_serializer': lambda x: list(str(z) for z in x.tolist()),
            'serde_deserializer': lambda x: np.array(x, dtype=np.cdouble),
        }
    )

    def __post_init__(self):
        self.a = np.array(self.a, dtype=np.cdouble)

# Create using a list
f = FooComplex(
        a=[
            complex(1., 2.),
            complex(3., 4.)
        ]
    )

# Check type of "f.a"
print(type(f.a))

# Serialize
print(to_json(f))

# Deserialize
s = '{"a": ["(1+2j)", "(3+4j)"]}'
print(from_json(FooComplex, s))

```

**python complex_number.py**
```bash
<class 'numpy.ndarray'>
{"a": ["(1+2j)", "(3+4j)"]}
FooComplex(a=array([1.+2.j, 3.+4.j]))
```

**Comment by yukinarit** [comment]
Hi @Besler 

Thanks for your post! 
I am not a numpy user but I would like to make pyserde easy to use with numpy.

pyserde used to have [more_types.py](https://github.com/yukinarit/pyserde/blob/28c8c1a824264cd36986332039b7357a620e2931/serde/more_types.py) to serialize/deserialize non primary types (e.g. Decimal), but later the module was deleted because pyserde officials supported Decimal, Pathlib ..etc. If we get `more_types.py` back again, is it the best place to put your numpy code? 🤔 

What do you think?

**Comment by Besler** [comment]
Yes, this would work! It would also be nice to include a (de)serialization for `complex` to avoid a string conversion. That is, avoid:
```python
s = '{"a": ["(1+2j)", "(3+4j)"]}'
```
and just have:
```python
s = '{"a": [1+2j, 3+4j]}'
```
