### ISSUE TITLE
Switch toml library to correctly handle Toml v1 standard

### ISSUE THREAD

**Issue by hiranp** [yukinarit/pyserde#154]
Please consider changing the current "toml" library dependency. It is not fully toml  v1 compliant. See: https://github.com/toml-lang/toml/wiki. 
I would recommend:
https://github.com/samuelcolvin/rtoml

**Comment by yukinarit** [comment]
@hiranp  Thanks for the suggestion! 

I would like to make pyserde work with other Toml libraries!

**Comment by yukinarit** [comment]
Hi @hiranp @Yura52 

Thanks for the comments!
I am thinking to make changes to `to_toml`/`from_toml` like this. `to_toml` and `from_toml` uses `toml` library as default, but you can always pass any toml compatible library (i.e. provides `dumps`, `loads`) as `se`/`de` arguments. With this change, you can use both `tomli` and `rtoml`.

```python
def to_toml(obj, se=toml, **opts) -> str:
    return se.dumps(to_dict(obj, reuse_instances=False), **opts)

def from_toml(c: Type[T], s: str, de=toml, **opts) -> T:
    return from_dict(c, de.loads(s, **opts), reuse_instances=False)
```

One downside is pyserde still depends on `toml` package. I would like to consider switching the default toml library when Python community decides to pick one for std.

What do you guys think?

**Comment by yukinarit** [comment]
Yeah, I am also thinking to adopt tomli 🙂
