### ISSUE TITLE
Feature request: add a "serde_skip_if_default" option

### ISSUE THREAD

**Issue by anthrotype** [yukinarit/pyserde#176]
hello, thanks for this nice library!

I know there's already "serde_skip" and "serde_skip_if" field metadata options. I'd like to be able to omit serializing optional attributes when the value is equal to their default value. 
One could use "serde_skip_if" but then one needs to repeat the default value twice, i.e. once in `field(default=...` and then again in `"serde_skip_if: lambda v: v == {{default value}}`.
So I'd like a `"serde_skip_if_default": True` that would basically do that.

Thanks in advance!

**Comment by anthrotype** [comment]
it would also be nice to be able to set that option more globally, e.g. at the class level (in the `@serialize` decorator maybe) in addition to for each field.

**Comment by yukinarit** [comment]
Hi @anthrotype 

Thanks for the interest and feature request! I can take a look at it after a few days. 🙂

**Comment by anthrotype** [comment]
Thank you!

**Comment by yukinarit** [comment]
@anthrotype Sorry for the delay, let me consider adding `skip_if_default` class attribute later 👍
