### ISSUE TITLE
pyserde-0.5.3 may not have been updated.

### ISSUE THREAD

**Issue by OhkuboSGMS** [yukinarit/pyserde#179]
First, thanks for this useful library !

I installed the latest version of pyserde, 0.5.3, from pip.

`from serde import serde` raise error, I checked `__init__.py `and found that `def serde` did not exist.
Just in case, I downloaded it directly from pipl and checked it, but `def serde` did not exist here either.
Perhaps something went wrong when uploading to the pypi.
Thank you for your confirmation.

------------------------

pip からpyserdeの最新バージョンである0.5.3をインストールしました．

`from serde import serde`ができなったため，インストールされた`serde/__init__.py`を確認してみたところ` def serde`が存在していませんでした．
念のため，PyPIから直接ダウンロードして確認してみましたが，こちらにも`def serde`は存在していませんでした．
おそらく，pypiにアップロードする際に何らかも間違いがあった可能性があります．
ご確認の方よろしくお願いします

pypi上の pyserde0.5.3のリンク
https://files.pythonhosted.org/packages/49/c9/e426f28380ed62386519fee8dbf875627ed871c338393a5d4e7b7648fbec/pyserde-0.5.3.tar.gz

**Comment by yukinarit** [comment]
Hi @OhkuboSGMS 

Thanks for your interest! 

`serde` decorators exists in `master` branch as of now, and this upcoming version (to be `v0.6.0) is not yet published in PyPI. 

I am planning to merge a few more changes and push to PyPI in the next few days, so please be patient. If you are in a hurry, please refer to the v0.5.3 documentation: https://github.com/yukinarit/pyserde/tree/v0.5.3

---

pyserdeに興味を持ってくれてありがとうございます！

`serde`デコレータは次のバージョン用(v0.6.0)の新しい機能でまだPyPIで公開されていません。あといくつかマージして数日中にv0.6.0を公開予定ですが、お急ぎならv0.5.3のドキュメントやサンプルコードを確認ください https://github.com/yukinarit/pyserde/tree/v0.5.3 

よろしくお願いします。

**Comment by OhkuboSGMS** [comment]
thank you for your reply.
I misunderstood that the serde decorator was implemented in 0.5.3.

I look forward to the 0.6.0 update.
***

返信ありがとうございます。
0.5.3でserdeデコレータが実装されていると，勘違いしていました．

0.6.0のアップデートを楽しみにします．
