### ISSUE TITLE
Ensure docs track the latest release tag

### ISSUE THREAD

**Issue by benridley** [yukinarit/pyserde#180]
Thanks @yukinarit and others for an awesome library, this is exactly what I wanted when working with dataclasses.

I did have some issues though, because I noticed that the documentation at https://yukinarit.github.io/pyserde/guide/ is using what appears to be the master branch of the code, however when I tried installing pyserde and using it, I noticed I couldn't import the `serde` function. After some digging, it appears this is because the published pypi package is using the 0.5.3 tag which doesn't that function.

It might be a good idea to ensure the published documentation matches the published package, so users aren't confused when the examples etc in the documentation don't work for them.

Thanks!

**Comment by yukinarit** [comment]
Hi @benridley 

Thanks for liking `pyserde`!

Sorry about the confusion. I was told by the other person also. 
I will work on publishing v0.6.0 and [hosting multiple versions of documentation](https://github.com/yukinarit/pyserde/issues/117) ASAP.

**Comment by benridley** [comment]
Thanks @yukinarit, I appreciate your awesome work!

**Comment by yukinarit** [comment]
sorry for the delay, the documentation is now published on release.
