### ISSUE TITLE
'NoneType' object is not iterable when deserializing list field with None value

### ISSUE THREAD

**Issue by baltek71** [yukinarit/pyserde#188]
Hi, 
I'm trying to deserialize dict into obj with list field that can be None.

Python 3.9 pyserde==0.6.0
```
from typing import List
from serde import serde, from_dict, field

@serde
class Foo:
    bar: List[int] = field(default_factory=list, skip_if_false=True)
    
from_dict(Foo, {"bar": None})
```

which throws TypeError
```
     return serde_scope.funcs[FROM_DICT](o, reuse_instances=reuse_instances)
  File "<string>", line 9, in from_dict
TypeError: 'NoneType' object is not iterable
```

I also tried to use:
`bar: List[int] = field(default_factory=list, skip_if=lambda v: v == None)` and
`bar: List[int] = field(default=None, skip_if_default=True)` 
but it gave the same results. 

Can you help me achieve this ? I want to keep field type annotation.
I checked skip examples but list field is always passed as [] there.

**Comment by yukinarit** [comment]
Hi @baltek71 

It sounds like a bug. Let me work on it after https://github.com/yukinarit/pyserde/issues/142

For now, is it possible to use this workaround? 

```python
@serde
class Foo:
    bar: Optional[list[int]] = field(default_factory=list)
```

**Comment by baltek71** [comment]
Thanks, I haven't thought of that ! 
Using Optional type worked for me.
