### ISSUE TITLE
KeyError for Optional when using custom deserializer

### ISSUE THREAD

**Issue by smoehrle** [yukinarit/pyserde#190]
Hey,

just noticed your project today and played around a bit :+1:  

I just found out that the "Optional" detection/deserialization is not working anymore when using a custom deserializer. Example:

```python
from serde import serde, SerdeSkip
from serde.json import from_json
from dataclasses import dataclass
from typing import Optional


def des(cls, o):
  raise SerdeSkip()

@serde(deserializer=des)
@dataclass
class Foo:
  a: Optional[str]

print(from_json(Foo, '{"a": "foo}')) # -> Foo(a='foo')
print(from_json(Foo, '{}'))          # -> KeyError: 'a'
```

Greetings

**Comment by yukinarit** [comment]
Hi @smoehrle 
Sounds like a bug. Thanks for reporting!

**Comment by yukinarit** [comment]
@smoehrle 
I think the issue was resolved. Let me know if you find more issues. Thanks!
