### ISSUE TITLE
pyserde 0.7

### ISSUE THREAD

**Issue by carlocorradini** [yukinarit/pyserde#199]
In my project I need to use Union Representation, therefore tagging is mandatory.
However, pyserde 0.7 is necessary to use tagging.
How can I deal with that?
Or when it will be available on pypi?
Thanks!

**Comment by yukinarit** [comment]
Hi @carlocorradini, Thanks for being interested in pyserde!

I wanted to include the feature to address #164 in 0.7, but it seems I need more time to finish. 

Let me try to push pyserde 0.7 without #164 to PyPI by the weekend. If you need to test it right now, please install it from Git. Thanks.

**Comment by carlocorradini** [comment]
@yukinarit pyserde is awesome!
I've used rust so it's easy and powerful!

**Comment by carlocorradini** [comment]
@yukinarit a little help (I am new to Python)
I'm using `pipenv` trying to install pyserde via:
```bash
pipenv install -e "git+https://github.com/yukinarit/pyserde.git@master#egg=pyserde"
```
but i receive the following error(s):

![immagine_2022-02-02_142115](https://user-images.githubusercontent.com/21266147/152161766-b5ab29ea-391e-4a6e-bb57-09c6d06abde8.png)

Any help?

Thanks! 🤯

**Comment by yukinarit** [comment]
> pyserde is awesome!

I am glad to hear that! I also use Rust + serde a lot 😄 

> but i receive the following error(s):

It worked for me without `-e`.

```
pipenv install "git+https://github.com/yukinarit/pyserde.git@master#egg=pyserde"
```

---

If you are new to Python, I would recommend using Poetry. It's closer to Cargo.

```
pip install poetry
poetry init
poetry add pyerde
```

Goes into poetry environemnt
```
poetry shell
pip list # This should list pyserde
```

**Comment by carlocorradini** [comment]
Working.
Waiting for version 0.7.0 🎉

**Comment by yukinarit** [comment]
@carlocorradini I pushed 0.7.0 in PyPI!
