### ISSUE TITLE
MAC address support

### ISSUE THREAD

**Issue by carlocorradini** [yukinarit/pyserde#200]
I think it would be nice to support serialization/deserialization of MAC addresses.

This feature would go well with `ipaddress` data format.

**Comment by MrPerpe** [comment]
It would be AWESOME!

**Comment by yukinarit** [comment]
Do you have specific class to represent Mac address in mind? e.g. `ipaddress.IPv4Address` for IP address.

**Comment by carlocorradini** [comment]
@yukinarit what about [python-macaddress](https://github.com/mentalisttraceur/python-macaddress) ?
I also says: *Heavily inspired by the ipaddress module*

**Comment by carlocorradini** [comment]
@yukinarit 
*PS*: The `ipaddress` support is awesome! I've been using it extensively in my projects.
Thanks again for this library!

**Comment by yukinarit** [comment]
@carlocorradini 
Sorry, pyserde doesn't support third-party libraries unless it's important for everyone e.g. Numpy. 

How about using the custom field (de)serializer? 🤔 

```python
from serde import serde, field
from serde.json import to_json, from_json
from macaddress import EUI48

@serde
class Foo:
    addr: EUI48 = field(serializer=lambda x: str(x), deserializer=lambda x: EUI48(x))

f = Foo(EUI48('01-23-45-67-89-ab'))
print(f)
json_data = to_json(f)
print(json_data)
f = from_json(Foo, json_data)
print(f)
```

**Comment by carlocorradini** [comment]
@yukinarit  Awesome thanks!
For clarity, the serializer/deserializer can be defined only once and then each EUI48 is automatically (de)serialized? Or for each EUI48 I need to define `field(..)`

**Comment by carlocorradini** [comment]
@yukinarit
`addr` is optional. Unfortunately the following does not work:
```python
@serde
class Foo:
    addr: Optional[EUI48] = field(serializer=lambda x: str(x), deserializer=lambda x: EUI48(x))
```
Any idea?
Thanks

**Comment by yukinarit** [comment]
@yukinarit 

If you use custom (de)serializer, pyserde no longer handles Optional, Default .. etc. You need handle by yourself.

e.g.
```
@serde
class Foo:
    addr: EUI48 = field(serializer=lambda x: str(x), deserializer=lambda x: EUI48(x))
    opt_addr: Optional[EUI48] = field(serializer=lambda x: x and str(x), deserializer=lambda x: x and EUI48(x))
```

**Comment by carlocorradini** [comment]
@yukinarit Thanks!
