### ISSUE TITLE
mypy: Unexpected keyword argument

### ISSUE THREAD

**Issue by gitpushdashf** [yukinarit/pyserde#205]
Hi,

This is very cool!

Unfortunately, when I use `mypy`, I get `Unexpected keyword argument` when I try to `return` a `@serde`ed class from a function. I'm not sure if `serde` would need to have a `mypy` plugin or if I'm making a mistake.

I can make a minimal test case if needed.

Thank you!

**Comment by yukinarit** [comment]
Hi @gitpushdashf 

Yes, could you please provide a minimal test case? Thanks!

**Comment by gitpushdashf** [comment]
Sorry for the wait! Here it is:

```
(.venv) test-pyserde % cat test.py
from serde import serde

@serde
class Foo:
    i: int
    s: str


def make_a_foo(i: int, s: str) -> Foo:
    return Foo(i=i, s=s)


assert make_a_foo(5, "a") == Foo(i=5, s="a")
(.venv) test-pyserde % cat test.sh
mypy --strict .
python test.py
(.venv) test-pyserde % sh test.sh
test.py:10: error: Unexpected keyword argument "i" for "Foo"
test.py:10: error: Unexpected keyword argument "s" for "Foo"
test.py:13: error: Unexpected keyword argument "i" for "Foo"
test.py:13: error: Unexpected keyword argument "s" for "Foo"
Found 4 errors in 1 file (checked 1 source file)
```

**Comment by yukinarit** [comment]
Look like there is no good way to fix? https://mypy.readthedocs.io/en/stable/additional_features.html#caveats-known-issues

Another workaround:

```python
from serde import serde
from dataclasses import dataclass

@serde
@dataclass
class Foo:
    i: int
    s: str
```

**Comment by gitpushdashf** [comment]
Ah, I see.

Doesn't `@serde` already apply `@dataclass`? So `@dataclass` is applied twice? I'm not sure if that's an issue or not.

**Comment by yukinarit** [comment]
@gitpushdashf should be no problem! 👍

**Comment by gitpushdashf** [comment]
Thank you!
