### ISSUE TITLE
serde.compat.SerdeError: 'size' workaround

### ISSUE THREAD

**Issue by ryanrussell** [yukinarit/pyserde#212]
Hello,

I'm trying to use Serde on a `dict` with a nested `list of dicts` with 50k `dicts`.

```python
@serde
class Trade(object):
    ...
        
@serde
class Trades:
    results: list[Trade] = field(metadata={"serde_flatten": True})
    ...
    
def process_trades():
    ...
    trades = from_dict(Trades, data)
```

When I try to send batches of 50k, 
```bash
    trades = from_dict(Trades, data)
  File "/opt/bitnami/python/lib/python3.10/site-packages/serde/de.py", line 376, in from_dict
    return from_obj(cls, o, named=True, reuse_instances=reuse_instances)
  File "/opt/bitnami/python/lib/python3.10/site-packages/serde/de.py", line 353, in from_obj
    raise SerdeError(e)
serde.compat.SerdeError: 'size'
```

This error persists to the 3k batch size, when it changes to this error:
```bash
    trades = from_dict(Trades, data)
  File "/opt/bitnami/python/lib/python3.10/site-packages/serde/de.py", line 376, in from_dict
    return from_obj(cls, o, named=True, reuse_instances=reuse_instances)
  File "/opt/bitnami/python/lib/python3.10/site-packages/serde/de.py", line 353, in from_obj
    raise SerdeError(e)
serde.compat.SerdeError: 'conditions'
```

When I drop the batch size to 1k, it succeeds.

Took a quick look at [https://github.com/yukinarit/pyserde/blob/master/serde/de.py#L283](https://github.com/yukinarit/pyserde/blob/master/serde/de.py#L283), but did not see a param around handling large objects.

Is there a hard size limit somewhere?

Is there a way to tune the configuration to make it take larger objects? 

Thank you for any guidance.

**Comment by yukinarit** [comment]
Hi @ryanrussell !

There is no size limit in pyserde AFAIK. Does `Trade` class have `size` and `conditions` fields? 🤔

**Comment by ryanrussell** [comment]
Yes, it does! 

```python
@serde
class Trade(object):
    # {"conditions": [12, 41], "exchange": 11, "id": "1", "participant_timestamp": 1517562000015577000, "price": 171.55, "sequence_number": 1063, "sip_timestamp": 1517562000016036600, "size": 100, "tape": 3}
    conditions: list[int] = field(metadata={"serde_flatten": True})
    ...
    size: int
```

Let me investigate those issues, looks like it's probably a data validation error instead. Thanks so much for the help.

Will post back with a close to confirm when it works.

**Comment by yukinarit** [comment]
@ryanrussell 
Could you try to remove `field(metadata={"serde_flatten": True})`? 

```python
@serde
class Trade(object):
    conditions: list[int]
    ...
    size: int
```

**Comment by ryanrussell** [comment]
Just confirming this was an issue on the data hygiene.

I did take out the serde_flatten as well, thank you for the tips.

Appreciate you sharing your approach to wrapping dataclasses. Very clean and functional!
