### ISSUE TITLE
Package does not include py.typed file?

### ISSUE THREAD

**Issue by AustinScola** [yukinarit/pyserde#217]
Hi, I don't think the `py.typed` file is being included in the package.

I'm using mypy to type check code using `serde` and getting the following error:
```
error: Cannot find implementation or library stub for module named "serde"  [import]
note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

I haven't used poetry so I'm not exactly sure how to fix this.

**Comment by gitpushdashf** [comment]
I just installed pyserde 0.7.1 in Docker, and I see the py.typed file:

```
root@3b817927a1c2:/# ls /usr/local/lib/python3.10/site-packages/serde/py.typed
/usr/local/lib/python3.10/site-packages/serde/py.typed
```

**Comment by gitpushdashf** [comment]
May want to take a look at this: #205

**Comment by AustinScola** [comment]
Ahh, sorry for the false alarm. I'm running mypy in a venv and forgot to add `pyserde` to the venv!
