### ISSUE TITLE
Raising an exception in `__post_init__` results in `SerdeError`?

### ISSUE THREAD

**Issue by AustinScola** [yukinarit/pyserde#233]
I have a dataclass and I want do to some validation of the fields in `__post_init__`. If there is a problem I raise a custom exception. However, `pyserde` catches all exceptions in `from_obj`and raises a `SerdeError` instead? This isn't really what I want and I don't know if it if the best behavior in general?

**Comment by yukinarit** [comment]
Oh, I didn't take `__post_init__` into account when I fixed https://github.com/yukinarit/pyserde/commit/76b0aee

Any good idea to exclude `__post_init__` in try-cache..? 🤔

**Comment by AustinScola** [comment]
Hmm I think we might be able to examine the stacktrace with the `traceback` module to determine if the exception was thrown from `__post_init__`?
