### ISSUE TITLE
Replace stringcase with casefy

### ISSUE THREAD

**Issue by gitpushdashf** [yukinarit/pyserde#240]
stringcase is very old and likely abandoned (last publish in 2017). casefy looks to be a promising alternative that's maintained.

https://github.com/dmlls/python-casefy

Would you consider this? I haven't looked yet to see how much work the conversion would be.

**Comment by yukinarit** [comment]
Hi @gitpushdashf 

I am ok to change. Conversion is very simple. Would you like to contribute? 😄 

```
$ yukinari@mbp ~/r/pyserde (strict-type)> git grep stringcase

pyproject.toml:stringcase = "*"
serde/core.py:import stringcase
serde/core.py:        casef = getattr(stringcase, case, None)
serde/core.py:            raise SerdeError(f"Unkown case type: {f.case}. Pass the name of case supported by 'stringcase' package.")
````

**Comment by gitpushdashf** [comment]
Sure! Pull request is open and ready to go. Tests passing locally.
