### ISSUE TITLE
Upgrading to 0.9.0: error: Call to untyped function "serde" in typed context

### ISSUE THREAD

**Issue by gitpushdashf** [yukinarit/pyserde#258]
Hi,

Not sure what changed, but mypy is complaining with serde 0.9.0. I didn't get this error in the last release.

Anything that is decorated with `@serde` gets this error. I am using `type_checking=Strict`, not sure if it would make any difference.

Thank you!

**Comment by gitpushdashf** [comment]
Ok, so it is when I do `@serde(strict_checking=True)` or `@serde()`. `@serde` is fine. I am using `mypy --strict`.

**Comment by yukinarit** [comment]
@gitpushdashf Thanks for reporting! Let me check

**Comment by yukinarit** [comment]
@gitpushdashf 
Can you please verify with the above PR?

**Comment by gitpushdashf** [comment]
Awesome. Works for me, thank you!
