### ISSUE TITLE
An example of deserialising an Enum

### ISSUE THREAD

**Issue by rbuckland** [yukinarit/pyserde#26]
Does pyserde support serialising/deserialising an Enum, other than integers? 
I could not find an example.

**Comment by yukinarit** [comment]
Hi @rbuckland 

Thank you for being interested in pyserde. I did [a quick check](https://github.com/yukinarit/pyserde/pull/27):
* IntEnum is supported for JSON, MsgPack format as of now
    * Yaml raises an error when serializing/deserizing IntEnum
    * Toml serializes IntEnum as str not int
* Enum is not yet supported

But I have a plan to fully support enums for all types of formats.

**Comment by waszil** [comment]
Hi! Great package! The Enum/IntEnum support would be a nice feature!

**Comment by yukinarit** [comment]
HI @waszil 

Thank you for being interested in pyserde!
I'm planning to implement Enum/IntEnum soon. Hope you can wait :)

**Comment by yukinarit** [comment]
Hi @waszil @rbuckland 

PR for enum support was just merged. Please take a look!

For your case,

```python
my_enum_field: MyEnumClass.MEMBER
```

`MyEnuClmass.MEMBER` is not a type. Can you do like this?
```python
my_enum_field: MyEnumClass
my_enum_field: MyEnumClass = MyEnumClass.MEMBER  # if you want to set default
```

For more information about the usage, please check [the example](https://github.com/yukinarit/pyserde/commit/6dca2792c32ceadbfdbd6e8aa50c0ac511661e7d#diff-f440e1620fa9b196e9c6b4f0948ad3e6)

**Comment by waszil** [comment]
Wow, this is great! Thanks a lot!
