### ISSUE TITLE
`ClassVar`s don't get serialized?

### ISSUE THREAD

**Issue by AustinScola** [yukinarit/pyserde#296]
Example:
```from typing import ClassVar
from serde.se import serialize, to_dict

@serialize
class Foo:
    value: ClassVar[str] = "abc"

print(to_dict(Foo()))  # Prints {}
```

**Comment by yukinarit** [comment]
@AustinScola 
Sorry for the delay

Unfortunately [dataclasses.fields](https://docs.python.org/3/library/dataclasses.html#dataclasses.fields) doesn't iterate on classvars so we have no luck

**Comment by OriDevTeam** [comment]
Same situation here, the only way i found to do so is to implement a custom method that specifically looks on the dataclass object fields

**Comment by AustinScola** [comment]
Is there a way for `pyserde` to introspect the fields another way?

**Comment by yukinarit** [comment]
If you introspect `__annotations__` by yourself, it's possible IMO

```python
from dataclasses import dataclass
from typing import ClassVar

@dataclass
class C:
    c: ClassVar[int] = 10

print(C.__annotations__)
```

```
{'c': typing.ClassVar[int]}
```

**Comment by yukinarit** [comment]
I will look into this

**Comment by yukinarit** [comment]
@AustinScola @OriDevTeam 
Do you expect deserialization to work for ClassVar?

**Comment by AustinScola** [comment]
I care more about serialization. What are your thoughts around de?

**Comment by yukinarit** [comment]
I checked `pydantic`. `pydantic` doesn't serialize `ClassVar` too. 

I am thinking to add an option to enable ClassVar serialization. Deserialization still doesn't make sense to me, especially class value might be mutated by every one of the objects being deserialized. So I am thinking to implement only optional serialization.

**Comment by AustinScola** [comment]
An option sounds good to me. And I agree that deseralization would be kind of goofy

**Comment by yukinarit** [comment]
@AustinScola @OriDevTeam pyserde v0.9.8 was pushed!
