### ISSUE TITLE
Union with a single type is ignored for tagging

### ISSUE THREAD

**Issue by Kobzol** [yukinarit/pyserde#308]
Hi! I'm currently trying to use `pyserde` for serializing data classes that must have backwards compatibility, and for that I want to store something like `Union[TypeVersion1, TypeVersion2, TypeVersion3, ...]` and use (external) tagging so that the version of the used type is stored in the serialized data.

It works fine, however I noticed that when there is only a single type in the `Union`, then the tagging will be ignored. This is a problem for my use case, because even though right now I only have a single type, I will probably add more of them in the future (that's the point of the versioning), but I need to store the current version into the serialized data from the beginning, even though there is only a single type now.

Here's a code example:
```python
from typing import Union

from serde import ExternalTagging, serde, to_dict

@serde
class Inner1:
    a: int


@serde
class Inner2:
    b: int


UnionType = Union[Inner1]
# UnionType = Union[Inner1, Inner2]


@serde(tagging=ExternalTagging)
class Config:
    inner: UnionType

a = Config(inner=Inner1(a=5))
data = to_dict(a)
# Got: {'inner': {'a': 5}}
# Expected: {'inner': {'Inner1': {'a': 5}}}
```

When I add `Inner2` to the `Union` type, then it works as expected.

Is this some limitation of the `Union` type in Python or is this an explicit decision made by `pyserde` to "unwrap" single union types?

**Comment by yukinarit** [comment]
It seems single argument for `Union` is valid. I would never thought about this case 🤦 

![Screenshot 2023-02-18 at 10 11 22](https://user-images.githubusercontent.com/2347533/219823545-cccedd44-d54a-471a-85b5-74c2e50d6f7e.png)

https://docs.python.org/3/library/typing.html#typing.Union

**Comment by yukinarit** [comment]
There are two approaches to fix the issue. 

1. Coerce `Union[X]` to inner type `X` in every `is_xxxx` functions
https://github.com/yukinarit/pyserde/blob/21fccac7e42f2c246208c151962867b1c8fcb85b/serde/compat.py#L520-L769 

or

2. Alter `Field`'s type in `fields` method and treat the field as inner type. 
https://github.com/yukinarit/pyserde/blob/21fccac7e42f2c246208c151962867b1c8fcb85b/serde/core.py#L547-L558


Looks like `2` is clean and easy to fix 🤔

**Comment by Kobzol** [comment]
I'm not sure if I understood your response correctly, but I actually want to treat Union[X] as Union[X], not just X, which happens currently (probably typing.Union already does this coercion based on the docs?).

**Comment by yukinarit** [comment]
Oh, I misread your issue the other way around!

> Is this some limitation of the Union type in Python or is this an explicit decision made by pyserde to "unwrap" single union types?

pyserde doesn't unwrap single union types. It seems `Union[X]` becomes `X` at the interpreter level? 
```
>>> print(typing.get_origin(typing.Union[int,bool]))
typing.Union
>>> print(typing.get_origin(typing.Union[int]))
None

>>> print(typing.Union[int,bool])
typing.Union[int, bool]
>>> print(typing.Union[int])
<class 'int'>
```

**Comment by Kobzol** [comment]
Oh, I was a bit afraid that Python itself mangles this. This is just... so stupid, why include a special edge case that could be handled optionally... Anyway, this is probably not solvable by `pyserde`, because it looks like single type `Union`s are completely transparent. `pyserde` could offer its own `Union` as an alternative, but that's probably not worth it.

Well, I will solve it with some hack, like `Union[TypeV1, SomeTypeThatWillNotBeDeserialized]`. Closing this issue, maybe it will at least help someone else with a similar problem :)
