### ISSUE TITLE
Serialize dataclasses without `serde` decorator

### ISSUE THREAD

**Issue by Kobzol** [yukinarit/pyserde#309]
Hi, it's me again :grin: Sorry for spamming so many issues, but `pyserde` is simply the best serialization library for Python that I have encountered yet, so I'm now migrating code to it and thus have a lot of questions :D

I wonder if it would be possible to implement support for serializing fields with a dataclass type, even if that dataclass isn't marked with `@serde`. I suppose that it could work by dynamically generating the serializing/deserializing methods when the type is first encountered and then caching them. Since the decorator is not used on such dataclasses, it would behave like `@serde`, without any parameters.
Basically, if `pyserde` saw a dataclass without the serde scope attribute, it could dynamically add it to the dataclass (or create an out-of-band hashmap of such dataclass types, to avoid modifying them), generate the serialization/deserialization functions and then continue as normal.

I know that (Rust) `serde` can't really do this, but in Python this should be theoretically possible. I have two use-cases for this:
1) Some type analysers do not yet support the `@dataclass_transform` attribute and if I add `@serde` to a dataclass, they stop all type checking of the dataclass :( I encounter this with PyCharm, `pyright` works fine. I hope that this will get resolved in time, but it's still a complication for me.
2) It would enable serialization of dataclasses that cannot be decorated with serde, e.g. ones from external code. Currently it can be resolved e.g. with a wrapper dataclass and `flatten=True`, but it would be nice if it was supported directly.

    Even for dataclasses from my own code, most of them are just marked with `@serde` without any additional configuration, but I still have to sprinkle this serialization decorator everywhere. It would be nice if such dataclasses (that do not require any specialized serde options) could be serialized automatically, without them even knowing about serde.

Let me know what you think about this! I can also help with implementing this or some of the other issues if you can guide me a bit.

**Comment by yukinarit** [comment]
Hi @Kobzol 

Yes, I think this is possible. If you're interested in contributing, I would love to assist you 👍
