### ISSUE TITLE
Compatibility with attrs

### ISSUE THREAD

**Issue by tiptop96** [yukinarit/pyserde#31]
This library looks really interesting to me. But I need to support "attrs" in my project.

Is "pyserde" compatible with "attrs" and if not is this on the road map and how hard would it be to support it?

**Comment by yukinarit** [comment]
Hi @tiptop96 

Thanks for your interest! Sorry, I'm not an `attr` user. Could you elaborate on what sort of compatibility you need? You want to use both attr decorator and pyserde decorator for your class? 🤔

**Comment by tiptop96** [comment]
Yeah, basically I would like to replace the @dataclass decorator with @attr.s

There are a few features from attrs like defaults and validation that I need. 😊

It's not an emergency as there are specific tools that were designed to do this for attrs, like cattrs. But, being a fan of rust this API had me curious.

**Comment by tiptop96** [comment]
Oh and also you support switching the casing of keys which is something I have had to implement myself when using cattrs.

**Comment by yukinarit** [comment]
It seems we need an abstraction over dataclass functions such as `astuple`, `asdict` and `fields`. It might not be done quickly but let me play around a bit more.

**Comment by yukinarit** [comment]
Sorry I can not come up with a good way to support attrs
