### ISSUE TITLE
Strict type checking not working for Optional

### ISSUE THREAD

**Issue by Fredrik-Reinholdsen** [yukinarit/pyserde#330]
Noticed that strict type checking does not seem to work properly for Optional[T]
For Example:

```python
import serde
from dataclasses import dataclass
from typing import Optional


@serde.serde(type_check=serde.Strict)
@dataclass
class Struct:
    value: int
    some: Optional[int]

print(serde.from_dict(Struct, {"value": 123, "some": "123"}))
```
returns Struct(value=123, some="123") when it should fail the type check for the inner type.

**Comment by yukinarit** [comment]
@Fredrik-Reinholdsen v0.10.3 is published in PyPI, Thanks!

**Comment by Fredrik-Reinholdsen** [comment]
No problem.
Thank you for your work and for a wonderful Python package!
