### ISSUE TITLE
Flatten type annotation is wrong?

### ISSUE THREAD

**Issue by AustinScola** [yukinarit/pyserde#355]
It seems there is a confusion about if the `flatten` arg for `field` is a `bool` or `FlattenOpts`? The examples show a bool but it is typed as `Optional[[serde.core.FlattenOpts]`.

**Comment by yukinarit** [comment]
I found this bug a few days ago and this will be fixed in the next version 👍

**Comment by yukinarit** [comment]
@AustinScola Published v0.10.7
