### ISSUE TITLE
Pylance reportUnknownVariableType: Type of "..." is partially unknown

### ISSUE THREAD

**Issue by davetapley** [yukinarit/pyserde#366]
e.g.:
```py
from serde.yaml import to_yaml
```

Will complain:
```
type of "to_yaml" is partially unknown
    Type of "to_yaml" is "(obj: Unknown, se: Type[Serializer] = YamlSerializer, **opts: Unknown) -> str" (reportUnknownVariableType)
```

I think a liberal scattering of `Any` would work around it, e.g.:

https://github.com/yukinarit/pyserde/blob/a9f44d52d109144a4c3bb93965f831e91d13960b/serde/yaml.py#L27

should be:
```py
def to_yaml(obj: Any, se: Type[Serializer] = YamlSerializer, **opts: Any) -> str:
```

---

A _more correct_ approach might be [something like this](https://stackoverflow.com/a/55240861/21115), to give:
```py
def to_yaml(obj: IsDataclass, se: Type[Serializer] = YamlSerializer, **opts: Any) -> str:
```

**Comment by yukinarit** [comment]
I am not a pylance user. I tested with mypy and pyright. 
PTAL this PR resolves your issue
https://github.com/yukinarit/pyserde/pull/367

**Comment by davetapley** [comment]
#367 fixes it, thanks for the fast reply 🙏🏻 

---

While we're on it, I have another `reportUnknownVariableType` for you, this time with `serde.field`:

Starting with:
https://github.com/yukinarit/pyserde/blob/47a4b0a279490a61966025a5a86e53022c43034a/docs/features/custom-field-serializer.md?plain=1#L13-L14

I have to extract the `lambda` to avoid
```
Return type of lambda is unknown Pylance[reportUnknownLambdaType]`
```

Fine:

```py
def serializer(x: datetime):
    return x.strftime('%d/%m/%y')

def deserializer(x: str):
     datetime.strptime(x, '%d/%m/%y')

dt2: datetime = field(serializer=serializer, deserializer=deserializer)
```

But now I get:
```
Type of "dt2" is partially unknown Type of "dt2" is "Unknown | datetime"Pylance[reportUnknownVariableType]
```

I don't know why `Unknown`, because:
https://github.com/yukinarit/pyserde/blob/47a4b0a279490a61966025a5a86e53022c43034a/serde/core.py#L369

But it gets weirder:

If I wrap with `typing.cast`:
```py
dt2: datetime = cast(dataclasses.Field[datetime], field(serializer=serializer, deserializer=deserializer)
```

I get:

```
Expression of type "Field[datetime]" cannot be assigned to declared type "datetime"
  "Field[datetime]" is incompatible with "datetime"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
```

Which led me to discover that if I:
```py
test_field = dataclasses.field(default=1) 
```

then `test_field` is inferred as `int`, not `dataclasses.Field[datetime]`,
which I _guess_ is a hack to make the typing work 😑 

So one workaround is:
```py
dt2: datetime = cast(datetime, field(serializer=serializer, deserializer=deserializer)
```

But I wonder if there is some way to have `serde.field` return the same 'fake' type? 🤔

**Comment by yukinarit** [comment]
@davetapley Made a new issue #370
