### ISSUE TITLE
Pylance error from serde.field

### ISSUE THREAD

**Issue by yukinarit** [yukinarit/pyserde#370]
#367 fixes it, thanks for the fast reply 🙏🏻 

---

While we're on it, I have another `reportUnknownVariableType` for you, this time with `serde.field`:

Starting with:
https://github.com/yukinarit/pyserde/blob/47a4b0a279490a61966025a5a86e53022c43034a/docs/features/custom-field-serializer.md?plain=1#L13-L14

I have to extract the `lambda` to avoid
```
Return type of lambda is unknown Pylance[reportUnknownLambdaType]`
```

Fine:

```py
def serializer(x: datetime):
    return x.strftime('%d/%m/%y')

def deserializer(x: str):
     datetime.strptime(x, '%d/%m/%y')

dt2: datetime = field(serializer=serializer, deserializer=deserializer)
```

But now I get:
```
Type of "dt2" is partially unknown Type of "dt2" is "Unknown | datetime"Pylance[reportUnknownVariableType]
```

I don't know why `Unknown`, because:
https://github.com/yukinarit/pyserde/blob/47a4b0a279490a61966025a5a86e53022c43034a/serde/core.py#L369

But it gets weirder:

If I wrap with `typing.cast`:
```py
dt2: datetime = cast(dataclasses.Field[datetime], field(serializer=serializer, deserializer=deserializer)
```

I get:

```
Expression of type "Field[datetime]" cannot be assigned to declared type "datetime"
  "Field[datetime]" is incompatible with "datetime"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
```

Which led me to discover that if I:
```py
test_field = dataclasses.field(default=1) 
```

then `test_field` is inferred as `int`, not `dataclasses.Field[datetime]`,
which I _guess_ is a hack to make the typing work 😑 

So one workaround is:
```py
dt2: datetime = cast(datetime, field(serializer=serializer, deserializer=deserializer)
```

But I wonder if there is some way to have `serde.field` return the same 'fake' type? 🤔

_Originally posted by @davetapley in https://github.com/yukinarit/pyserde/issues/366#issuecomment-1572873429_

**Comment by yukinarit** [comment]
@davetapley Do you have settings enabled? It didn't reproduce in my vscode 🤔

**Comment by davetapley** [comment]
@yukinarit whelp, no idea, I just removed the `cast` and no error now 🤪 

I've bumped quite a few versions since back then, so assume it got fixed upstream 🎉

**Comment by yukinarit** [comment]
@davetapley Good to hear that :tada:
