### ISSUE TITLE
Mark class as str serializable?

### ISSUE THREAD

**Issue by AustinScola** [yukinarit/pyserde#404]
If I have a class that I would like to be serialized with `str` is there a way I can mark it (and all subclasses) as such?

**Comment by yukinarit** [comment]
I still can not imagine what it is like. Can you please give me an example?

**Comment by AustinScola** [comment]
One example is that I have some subclasses of `pathlib.Path` that would like to easily serialize/deserialize.

**Comment by yukinarit** [comment]
It should be possible using pyserde v0.13 new custom class serializer. Please take a look at the following documentation and let me know if this is still not resolved. https://github.com/yukinarit/pyserde/blob/main/docs/en/class-attributes.md#class_serializer--class_deserializer
