### ISSUE TITLE
custom deserializer should be used on list items

### ISSUE THREAD

**Issue by BaxHugh** [yukinarit/pyserde#422]
Hi,
Thanks for this fantastic package!

If I have a custom deserializer for a class, it will not be used to deserialize objects in a list, which I feel it should. To deserialise a list of objects with a custom deserializer for the list of objects, I have to specify the custom deserializer for this list of objects. This is also problematic due to the fact that pyserde sees a list of objects as a `typing.List` which doesn't match python's `list` so a simple `if cls is list[Foo]` doesn't work.

This example documents the current and expected ideal behaviour.

Please let me know if there is a flag somewhere that I've missed which enables this behaviour.

```python
import typing
from typing import TypeVar

import serde
import serde.json

T = TypeVar("T")


def custom_deserialize_that_works(cls: type[T], o: dict) -> T:
    """Append 'custom' to the end of the foo string in a Foo."""
    if cls is Foo:
        # This doesn't get called for items in list[Foo], only for Foo itself.
        foo = Foo(**o)
        foo.foo = foo.foo + " custom"
        return foo
    if cls is list[Foo]:
        # This won't be called because for a list, cls is typing.List which does not match list[Foo]
        return [custom_deserialize_that_works(Foo, item) for item in o]
    if cls is typing.List[Foo]:  # noqa: UP006
        # This will be called because for a list[Foo], cls is typing.List[Foo]
        return [custom_deserialize_that_works(Foo, item) for item in o]
    else:
        raise serde.SerdeSkip


def custom_deserialize_ideal(cls: type[T], o: dict) -> T:
    """Append 'custom' to the end of the foo string in a Foo."""
    if cls is Foo:
        # Only specify custom for the class and this should be used for lists and nested objects
        foo = Foo(**o)
        foo.foo = foo.foo + " custom"
        return foo
    else:
        raise serde.SerdeSkip


@serde.serde
class Foo:
    foo: str


# Apply the serde decorator in main to show the two cases
class Foos:
    unlisted_foo: Foo
    foos: list[Foo]


if __name__ == "__main__":
    data = """
{
    "unlisted_foo": {"foo": "foo0"},
    "foos": [
        {"foo": "foo1"},
        {"foo": "foo2"}
    ]
}
"""
    # This works in the current pyserde 1.12.2
    serde.serde(Foos, deserializer=custom_deserialize_that_works)

    foos = serde.json.from_json(Foos, data)
    assert foos.unlisted_foo.foo == "foo0 custom"
    assert foos.foos[0].foo == "foo1 custom"

    # This doesn't work but ideally it should.
    serde.serde(Foos, deserializer=custom_deserialize_ideal)
    foos = serde.json.from_json(Foos, data)
    assert foos.unlisted_foo.foo == "foo0 custom"
    assert foos.foos[0].foo == "custom foo1"  # This fails because the deserializer doesn't propagate through lists.

```

**Comment by yukinarit** [comment]
@BaxHugh 
Hi sorry for the delay! (I am back from vacation)

yeah, current custom deserializer is not really handy, you need to take care of all the possible types. I am thinking if we could implement a more flexible custom deserializer facility like Rust's trait system using [plum](https://github.com/beartype/plum) .. :thinking: 

If you are interested in contributing, I am happy to assist you.

**Comment by yukinarit** [comment]
@BaxHugh New custom class serializer should resolve your issue. Please take a look and reopen if this is still the issue :pray:  https://github.com/yukinarit/pyserde/blob/main/docs/en/class-attributes.md#class_serializer--class_deserializer
