### ISSUE TITLE
Is there a way to have a customer serializer for a whole class (vs. for the class of an attribute of an object)

### ISSUE THREAD

**Issue by morrison12** [yukinarit/pyserde#424]
I would like to be able to supply a custom serializer for a whole object (whether `dataclass` or not) and not just for attributes.
I tried the naive approach as shown below but it didn't work.
Is there a way to have `serde` apply a serializer to a whole object ?

with `python 3.10.2` and `pyserde==0.12.2` running the code below gives:
`{"a":1,"b":{"x":"fun","y":"stuff"},"c":"end"}`
where I wanted to see:
`{"a":1,"b":"fun stuff","c":"end"}`

``` python

from __future__ import annotations
from dataclasses import dataclass
from serde import serde, SerdeSkip
from serde.json import to_json
from typing import Any


def serialize_foo(cls: type[Any], o: Any) -> str:
    if cls is Foo:
        return f"{o.a} {o.b}"
    raise SerdeSkip


def deserialize_foo(cls: type[Any], o: Any) -> Foo:
    if cls is Foo:
        return Foo(*o.split(" "))
    raise SerdeSkip


@serde(serializer=serialize_foo, deserializer=deserialize_foo)
@dataclass
class Foo:
    x: str
    y: str


@serde
@dataclass
class Bar:
    a: int
    b: Foo
    c: str

print(to_json(Bar(1, Foo("fun", "stuff"), "end")))```

**Comment by yukinarit** [comment]
@morrison12 Please use new custom class serializer. For now let me close this issue. You can reopen if you still have this issue. 
https://github.com/yukinarit/pyserde/blob/main/docs/en/class-attributes.md#class_serializer--class_deserializer
