### ISSUE TITLE
Keep order of serialized dataclasses fields as defined for YAML format

### ISSUE THREAD

**Issue by msurkovsky** [yukinarit/pyserde#426]
I'd like to keep the order of items in resulting YAML file as defined in program, e.g.:

```python
@serde
@dataclass
class Content:
  foo: Foo
  bar: Bar

@serde
@dataclass
class Config
  content: Content
```

I'd like to have yaml file following the order of arguments as defined in the class:
```yaml
content:
  - foo
  - bar
```

and not ordered alphabetically:
```yaml
content:
  - bar
  - foo
```

Is it possible to achieve this behavior in the current version? Thank you!

**Comment by yukinarit** [comment]
Hi @msurkovsky 
Will [this](https://github.com/yukinarit/pyserde/issues/344#issuecomment-1556145753) help?

**Comment by msurkovsky** [comment]
Hi @yukinarit

Yes this is exactly what I was looking for. Thank you!
