### ISSUE TITLE
`alias` on `Optional` field breaks deserialization

### ISSUE THREAD

**Issue by opeik** [yukinarit/pyserde#429]
Hi there,

Using the latest version (0.12.2), this example consistently deserializes `Foo.a` to `None`:
```py
@serde
@dataclass
class Foo:
    a: Optional[int] = field(alias=["b"])

x = from_json(Foo, '{"b": 1}')
assert x.a == 1 💥
```

**Comment by yukinarit** [comment]
@opeik 
Thanks for reporting! It was fixed in v0.12.3 :rocket:
