### ISSUE TITLE
tagging with InternalTagging not working when serialize dataclass

### ISSUE THREAD

**Issue by MaiHoangViet1809** [yukinarit/pyserde#443]
version: 0.12.5
When I create dataclass and tagging it with InternalTagging("sometag"), using default to_json, to_dict won't create that tagging in the output, is this default behavior or something wrong ?
example:
```
from dataclasses import dataclass
from serde import serde, to_dict, InternalTagging

@serde(tagging=InternalTagging("sometag"))
@dataclass
class SomeMessage:
    a: str
    b: int

    def serialize(self):
        return to_dict(self, InternalTagging("sometag", self.__class__))
        
new_obj = SomeMessage(a="aaa", b=1)
print(new_obj.serialize())

# stdout:: {'a': 'aaa', 'b': 1}

# expected output:: {'sometag': 'SomeMessage', 'a': 'aaa', 'b': 1}
```
the key sometag not exist in output as expected...

**Comment by yukinarit** [comment]
Hi @MaiHoangViet1809 

Tagging is for Union. This is an example.

```rust
from dataclasses import dataclass
from serde import serde, to_dict, InternalTagging # E: F401 [*] `serde.serde` imported but unused
from typing import Union


@dataclass
class MessageA:
    a: str

@dataclass
class MessageB:
    b: int


message_a = MessageA("aaa")
print(to_dict(message_a, InternalTagging("sometag", Union[MessageA, MessageB])))

message_b = MessageB(1)
print(to_dict(message_b, InternalTagging("sometag", Union[MessageA, MessageB])))
```

It prints

```
{'a': 'aaa', 'sometag': 'MessageA'}
{'b': 1, 'sometag': 'MessageB'}
```

**Comment by MaiHoangViet1809** [comment]
Ofc tagging for union type, I think we need a document for triggering this behavior using union type.
IMO, should make this behavior default or create config switch to let user turn it on, since in micro service, you won't know in advance which final union type will be use, only know current data-class in current service.

**Comment by yukinarit** [comment]
@MaiHoangViet1809 
There is actually a document about Union. Have you seen this page? https://yukinarit.github.io/pyserde/guide/en/union.html
