### ISSUE TITLE
Union example does not seem to work out of the box

### ISSUE THREAD

**Issue by nicoddemus** [yukinarit/pyserde#449]
Hi!

First of all thanks for the great library.

I was following the docs at https://github.com/yukinarit/pyserde/blob/main/docs/en/union.md, and the second example shows that this should work out of the box:

```python
from dataclasses import dataclass
from typing import Union

from serde import serde
from serde.json import to_json, from_json

@serde
@dataclass
class Foo:
    a: int

@serde
@dataclass
class Bar:
    a: int

bar = Bar(10)
s = to_json(bar)
print(s)
print(from_json(Union[Foo, Bar], s))
```

(I added the imports to have a ready to run example).

However using Python 3.11 and `pyserde-0.12.6`, I get this error:

```
{"a":10}
Traceback (most recent call last):
...
serde.compat.SerdeError: Can not deserialize {'a': 10} of type Dict into Union[Foo, Bar].
Reasons:
 Failed to deserialize into Foo: 'Foo' key is not present
 Failed to deserialize into Bar: 'Bar' key is not present
```

Looking at the first print (`{"a":10}`) it is not using the external tagging as mentioned in the documentation.

If I explicitly use external tagging:

```python
bar = Bar(10)
s = to_json(bar, cls=ExternalTagging(Union[Foo, Bar]))
print(s)
print(from_json(ExternalTagging(Union[Foo, Bar]), s))
```

Then it works:

```
{"Bar":{"a":10}}
Bar(a=10)
```

Am I doing something wrong?

If this is just a documentation issue, would be happy to supply a PR fixing it.

**Comment by yukinarit** [comment]
@nicoddemus 
Seems like a documentation bug. Thanks for reporting!

**Comment by nicoddemus** [comment]
Awesome, thanks!
