### ISSUE TITLE
Issue using class serializers/deserializers with new plum-dispatch version

### ISSUE THREAD

**Issue by Sh1nku** [yukinarit/pyserde#469]
It seems that `plum-dispatch` `2.3.x` breaks `class_serializers` and `class_deserializers`.
In `pyserde`'s config file the dependency is not pinned, so it'll choose the newest version (Currently `2.3.2`).
https://github.com/yukinarit/pyserde/blob/03c0c1f5e1fd744e1cf3ad4dce3ce0e5278ecb20/pyproject.toml#L44

Running the test suite on the `main` branch or the `v0.13.0` tag causes all `class_(de)serializer` tests to fail with the following message.
```
>                   implemented_methods[sig.types[1]] = n
E                   AttributeError: 'Method' object has no attribute 'types'

FAILED tests/test_custom.py::test_custom_class_serializer - AttributeError: 'Method' object has no attribute 'types'
FAILED tests/test_custom.py::test_custom_serializer_with_class_attributes - AttributeError: 'Method' object has no attribute 'types'
...
```

Manually forcing `plum-dispatch` to `2.2.2` seems to make things work again. I have not done any deeper investigation into what actually breaks.

**Comment by yukinarit** [comment]
@Sh1nku 
Thanks, Let me take a look.

**Comment by Sh1nku** [comment]
Thank you!
