### ISSUE TITLE
Incorrect deserialization when deserializing a Union[list, object]

### ISSUE THREAD

**Issue by roosephu** [yukinarit/pyserde#472]
Code to reproduce: 

```python
import serde
from dataclasses import dataclass

@serde.serde
@dataclass
class A:
    a: int

@serde.serde(tagging=serde.InternalTagging('type'))
@dataclass
class B:
    x: list[int] | A

o = B(x=A(a=1))
serde.json.from_json(B, serde.json.to_json(o))
```

Expect:
`B(x=A(a=1))`

Output:
`B(x=['a', 'type'])`

**Comment by yukinarit** [comment]
Thanks @roosephu for reporting! Let me take a look.

**Comment by yukinarit** [comment]
Hi @roosephu 

internal tagging basically works only for dataclass only.

e.g. dataclass

```python
@serde(tagging=InternalTagging("type"))
class Foo:
    a: Union[Bar, Baz]
```
this class will serialize to `{"a": {"type": "Baz", "b": 10}}`

however, 

e.g. list

```python
@serde(tagging=InternalTagging("type"))
class Foo:
    a: Union[Bar, list[int]]
```
this class will not be able to have `type` anywhere inside list.

pyserde silently ignores tags when non dataclass is used in union. I guess pyserde should raise an error to prevent misusage.
