### ISSUE TITLE
Bear type checking "leaks" to classes without the @serde decorator

### ISSUE THREAD

**Issue by nicoddemus** [yukinarit/pyserde#480]
Hi,

With update 0.14, it seems that bear type checking is being applied to classes passed as arguments to `serde.json.to_json`, even if they do not have the `@serde` decorator applied to them.

In general I prefer to not use the `@serde` decorator in my model classes, instead using `serde` only at the I/O layer with the `serde.json.from_json` and `serde.json.to_json` functions.

However seems like after calling `to_json` into a dataclass without the `@serde` decorator, bear type checking is now applied to that class from that point onward, which is surprising.

Example:

```python
from dataclasses import dataclass

import serde.json


@dataclass
class Foo:
    value: int


# This passes.
f = Foo("100")

data = serde.json.to_json(f, cls=Foo)

# After to_json(), this starts to fail with:
# beartype.roar.BeartypeCallHintParamViolation: Method __main__.Foo.__init__() parameter value='100' violates type hint <class 'int'>, as str '100' not instance of int.
f = Foo("100")
```

This is surprising to the user, even more so because model classes start to validate their types *after* some I/O has been performed, which might happen at different points in the application.

A workaround for now is to decorate `Foo` with `@serde(type_check=disabled)`, however this is not ideal given the functions `to_json` and `from_json` do not convey that they might change the runtime behavior of the class being passed as parameter.

> [!Note]
> This example is simplified, but in my code it was more complex, where I had an attribute declared as `tuple[int, ...]` but would accept any `Sequence[int]` at runtime, being converted to `tuple[int, ...]` during `__post_init__` to ensure the constructed object would have the correct runtime type. The reason for this is that the `Sequence[int]` comes from an external source, and sometimes would be provided as `list[int]` or `tuple[int, ...]`.

**Comment by yukinarit** [comment]
Hi @nicoddemus 
Sorry for breaking your code. I would have not expected this case. 

How about not implementing `@beartype` when pure dataclass is passed in `from_json`/`to_json` .. etc?

**Comment by nicoddemus** [comment]
Thanks @yukinarit for the quick response.

> Sorry for breaking your code. I would have not expected this case.

Oh absolutely no worries, I know it happens.

> How about not implementing @beartype when pure dataclass is passed in from_json/to_json .. etc?

You mean they won't be type-checked by @beartype? Actually that is what I would expect, I wouldn't expect `pyserde` to change the runtime behavior of the classes being passed to `from_json`/`to_json`. Now when you decorate the class, that's another story, it is expected that some behavior will be applied to the class.

**Comment by yukinarit** [comment]
> You mean they won't be type-checked by https://github.com/beartype?
Yes, that is what I mean. 

Alright, maybe I can take a look on this weekend.

**Comment by yukinarit** [comment]
Thanks! Merging :rocket:
