### ISSUE TITLE
Add example of a field with default_factory property

### ISSUE THREAD

**Issue by yukinarit** [yukinarit/pyserde#50]
Add in [examples/default.py](https://github.com/yukinarit/pyserde/blob/master/examples/default.py)

**Comment by pranavvp10** [comment]
Hi @yukinarit , can I work on it? by adding example you mean another dictionary like 's' in this default.py?

**Comment by yukinarit** [comment]
Hi @pranavvp10 
Of course, you can do it ;)
The dataclasses `default_factory` was supported since https://github.com/yukinarit/pyserde/pull/44

So, you will be adding a field like this

```python
d: Dict[str, int] = field(default_factory=dict)
```

You can check an example in [tests/test_basics.py](https://github.com/yukinarit/pyserde/blob/master/tests/test_basics.py#L256-L258).

---

After you modify, please try to run and verify `default.py` with this command

```
make setup examples
```

or

```
cd examples
pipenv run python defaut.tpy
```

Thank you!

**Comment by pranavvp10** [comment]
Hi, @yukinarit , When I modified and run default.py I got this output:
`Into Json: {"i": 10, "s": "foo", "f": 100.0, "b": true, "d": {}}
From Json: Foo(i=10, s='foo', f=100.0, b=True, d={})`

Is this the desired output?

I added the line `d: Dict[str,int] =field(default_factory=dict)`
and also added d in our dictionary s -> `s = '{"i": 10, "s": "foo", "f": 100.0, "b": true, "d":{}}'`

Thanks

**Comment by yukinarit** [comment]
@pranavvp10 
👍

**Comment by yukinarit** [comment]
Done in https://github.com/yukinarit/pyserde/pull/55
