### ISSUE TITLE
Investigate why coverage is not updated in coveralls 

### ISSUE THREAD

**Issue by yukinarit** [yukinarit/pyserde#52]
coverage report is not updated since Nov. 29, 2019? 🤔 
https://coveralls.io/github/yukinarit/pyserde?branch=master

**Comment by alexmisk** [comment]
Hi!

Are you considering changing Coveralls in favour of Codecov.io? If yes, I can update CI workflow with Codecov.io integration. Setting up Coveralls with Pytest and Github Actions seems like a harder task.

**Comment by yukinarit** [comment]
Hi! I don't mind in switching to codecov.io. Thanks for the great help!
