### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by yukinarit** [yukinarit/pyserde#545]
Can someone help?

**Comment by K-dash** [comment]
@yukinarit 
はじめまして！
yukinaritさんの[Zennの記事](https://zenn.dev/yukinarit/articles/7177ba04453e02)を見てpyserdeの存在を知りました。
とても魅力的なプロジェクトだと感じ、興味を持ってこちらのIssueにやってきました。

こちらのIssueですが、`docs/en/` 内のドキュメントを `docs/ja/` に翻訳する作業と認識していますが、この理解で正しいでしょうか？

もし可能であれば、このIssueを担当させていただきたいです。
pyserdeの理解を深めると共に、ドキュメントの翻訳を通じて本プロジェクトに貢献したいと思っています！

**Comment by yukinarit** [comment]
@K-dash 
ありがとうございます！とても嬉しいです！

> こちらのIssueですが、docs/en/ 内のドキュメントを docs/ja/ に翻訳する作業と認識していますが、この理解で正しいでしょうか？

この認識であっています。
[mdbook](https://github.com/rust-lang/mdBook)を使っています。ローカルで確認する場合は、以下のコマンドを使ってください :bow: 

```
cd docs/ja/
mdbook serve
```

他に質問等あればなんでも聞いてください！

**Comment by K-dash** [comment]
@yukinarit 
アサインありがとうございます！
mdbookでドキュメント確認できました。ご丁寧にありがとうございます  🙇

1点、進め方について確認させてください。
本作業業では1つのPRを作成し、当該PRに対して「1ドキュメント = 1コミット」という形で随時pushしていく流れで問題ないでしょうか？
もしくは、各ドキュメントごとにPRを分けた方がよろしいでしょうか？

pyserdeについて理解を深めながら作業を進めたいと考えており、全てのドキュメントを完成させるまでに少し時間をいただけると大変ありがたいです…！

ご指示いただけますと幸いです  🙇

**Comment by yukinarit** [comment]
1ページ、1コミットでも、1ページ1PRでもどちらでも大丈夫です！ :rocket:

**Comment by yukinarit** [comment]
@K-dash ありがとうございます！
おかげさまで日本語訳が完成しました :tada::+1::+1: 
とても助かりました

**Comment by K-dash** [comment]
@yukinarit 
PRのマージありがとうございます！本プロジェクトに少しでも貢献できたようで、とても嬉しいです🎉
おかげさまで今回のDoc翻訳作業を通じてpyserdeについて理解が深まりました。これからは積極的に使わせていただこうと思います💪
これからも本プロジェクトの発展、楽しみにしています！応援しています👍
