### ISSUE TITLE
Extra fields in dict are ignored, instead of throwing an error

### ISSUE THREAD

**Issue by spapinissi** [yukinarit/pyserde#596]
I want some way to throw an error if there is an error in the dict I'm loading, in the sense that it has extra irrelevant fields, not present in my class.

**Comment by yukinarit** [comment]
pyserde can detect and throw an error when
* required field is not found in dict
* value in dict does not match declared type

but pyserde can not detect unknown fields at the moment. this feature is equivalent to serde-rs's [#[serde(deny_unknown_fields)]](https://serde.rs/container-attrs.html).

**Comment by yukinarit** [comment]
> the alternative is that I move out codebase to marshmallow-dataclass, might be more work 😓 

Oh that is a trouble. I think I can take a look on this weekend!

**Comment by yukinarit** [comment]
@spapiniss `deny_unknown_fields` is available in v0.22.0 :rocket:

**Comment by spapinissi** [comment]
Amazing, it works! Thanks!
