### ISSUE TITLE
Deserializing Flattened fields with Defaults don't work together as expected

### ISSUE THREAD

**Issue by magreenberg1** [yukinarit/pyserde#610]
Hi @yukinarit - Love the project - Thank you for maintaining it! 

I noticed some unexpected behavior when deserializing flattened fields that have a default_factory. It looks like `pyserde` returns the defaults instead of the expected deserialized values. 

Here's the script I used:
```python
from serde import field, serde
from serde.json import from_json, to_json


@serde
class Bar:
    c: float = field(default=0.0)
    d: bool = field(default=False)


@serde
class Foo:
    a: int
    b: str
    bar: Bar = field(flatten=True, default_factory=Bar)


def main() -> None:
    f = Foo(a=10, b="foo", bar=Bar(c=100.0, d=True))
    json_str = to_json(f)

    print(f"Into Json: {json_str}")
    print(f"From Json: {from_json(Foo, json_str)}")


if __name__ == "__main__":
    main()

```

It prints:
```
Into Json: {"a":10,"b":"foo","c":100.0,"d":true}
From Json: Foo(a=10, b='foo', bar=Bar(c=0.0, d=False))
```
^ Notice how `bar` is deserialized with `c=0.0, d=False` instead of `c=100.0, d=True`

If happen to know where the problem is, I can draft a PR to fix it

**Comment by yukinarit** [comment]
Hi @magreenberg1!

Thanks for reporting. It seems like a bug. Let me look into it.

**Comment by yukinarit** [comment]
@magreenberg1 pyserde v0.22.2 was published in PyPI!

**Comment by magreenberg1** [comment]
Thank you!
