### ISSUE TITLE
Deserialization of extended types inside a container type fails

### ISSUE THREAD

**Issue by jfuechsl** [yukinarit/pyserde#66]
The following fails to deserialize. It seems that in the "more types" deserializer (for `Path`) the `Optional[Path]` field is passed. The deserializer in `more_types.py` then complains that `Optional` is an unsupported type. Same thing happens with other container types (e.g. `List`).
```
@deserialize
@dataclass
class Foo:
    bar: Optional[Path]

from_json(Foo, '{"bar": "/asdf"}')
```

**Comment by yukinarit** [comment]
@jfuechsl 
Thanks for reporting. I will take a look on this weekend 👍

**Comment by yukinarit** [comment]
Hi @jfuechsl 

Just let you know I made a fix. I will add a few more tests and release `0.2.1` this weekend :)

**Comment by jfuechsl** [comment]
Hi @yukinarit, thank you so much!

**Comment by yukinarit** [comment]
Hi @jfuechsl, pyserde 0.2.1 was released! Please check! ツ

**Comment by jfuechsl** [comment]
@yukinarit Thank you very much! It is fixed for me :)
