### ISSUE TITLE
Installed python might not be used in CI

### ISSUE THREAD

**Issue by yukinarit** [yukinarit/pyserde#67]
As you can see in the console, it's running in python 3.8 although it's during the `Python 3.7` stage.

<img width="1433" alt="Screen Shot 2020-11-16 at 18 54 50" src="https://user-images.githubusercontent.com/2347533/99238552-36a79300-283d-11eb-8716-78e16b44fecb.png">

It appears to me
* For `Ubuntu`: 
* For `macOS`: python3.8 is used during 3.6 / 3.7 / pypy3 stages
* For `Windows`: 
    * python 3.9 is used during 3.6 / 3.7 / 3.8 stages
    * python 3.7 is used during pypy stage

https://github.com/yukinarit/pyserde/runs/1404632126?check_suite_focus=true

@alexmisk Any idea? 🤔

**Comment by alexmisk** [comment]
Hey! 

Will work on it!
