### ISSUE TITLE
Supporting lazy deserialization

### ISSUE THREAD

**Issue by adsharma** [yukinarit/pyserde#81]
More context in: https://github.com/google/flatbuffers/issues/6428

Unlike msgpack, flatbuffers has the additional requirement that in a large type with many fields, if the caller is interested in deserializing only a couple of fields, they don't pay the cost of deserializing all fields.

Such a thing could be modeled as:

```
@dataclass
class LargeObject:
   _field1: type1
   _field2: type2
   ...
   _fieldN: typeN
   
   @lazy_property
   def field1():
      # Code to deserialize
      
   ...
```

I'm not sure if pyserde can provide an additional `@flatbuffer` decorator at some point with logic provided by the upstream projects. 

No change requested at this time. Putting this on your radar for future discussion.

**Comment by yukinarit** [comment]
Sorry I can't think how to implement this feature ...
