### ISSUE TITLE
Reject unformatted code by CI

### ISSUE THREAD

**Issue by yukinarit** [yukinarit/pyserde#88]

**Comment by alexmisk** [comment]
Hey! Looks like I can work on this. Which code style do you prefer? Black?

**Comment by yukinarit** [comment]
Hi @alexmisk  

pyserde use [black + isort](https://github.com/yukinarit/pyserde/blob/master/Makefile#L36-L38). Thanks!

**Comment by alexmisk** [comment]
Hi! In the _fmt_ section of the Makefile you are not passing the examples folder to isort. 

```
fmt:
	$(PIPENV) run black serde tests examples bench/bench.py
	$(PIPENV) run isort -rc --atomic serde tests bench/bench.py     <- no examples folder
```

Is this intentional? Should I configure CI checks in the same way?

**Comment by yukinarit** [comment]
Forgot to pass 😄 

Can you please add?
