### ISSUE TITLE
dict type in Union might be deserialized incorrectly

### ISSUE THREAD

**Issue by yukinarit** [yukinarit/pyserde#97]
@ydylla 
I think you are already aware of this issue but let me create this issue.

```python
@deserialize
@serialize
@dataclass
class Foo:
    c: Union[List[int], Dict[str, int]]

s = '{"c": {"bar": 1, "baz": 2}}'
print(f"From Json: {from_json(Foo, s)}")
```

I expect this will print 

```
From Json: Foo(c={'bar': 1, 'baz': 2})
```

but it is actually

```
From Json: Foo(c=['bar', 'baz'])
```

---

This is the generated deserialize code:

```python
def union_de_List_int__Dict_str_int_(data, reuse_instances):
  Foo = serde_scope.types['Foo']

  # create fake dict so we can reuse the normal render function
  fake_dict = {"fake_key":data}

  error = "Exhausted all types"
  try:
    return [v for v in fake_dict["fake_key"]]
  except Exception as e:
    error = str(e)

  try:
    return {k: v for k, v in fake_dict["fake_key"].items()}
  except Exception as e:
    error = str(e)

  raise SerdeError("Can not deserialize " + repr(data) + " of type " + typename(type(data)) + " into Union[List[int], Dict[str, int]]. Reason: " + error)
```

**Comment by ydylla** [comment]
Yes, I did not want to add instance checks for the deserialization, to keep it as fast as possible.   
One could workaround this problem by listing the most complex types first.   
Like I did here: https://github.com/yukinarit/pyserde/pull/87/commits/36c7095b63ebf490aa9ff7b5ce35b504bd46fc0f

**Comment by yukinarit** [comment]
Hi @ydylla  

> Yes, I did not want to add instance checks for the deserialization, to keep it as fast as possible.

Yes, I agree with you. But I want pyserde to be as easy to use as possible 🙂 

How about reordering the code generation of inner types?

If pyserde automatically finds a type like `Union[List[int], Dict[str, int]]`, it will generate code as if `Union[Dict[str, int], List[int]]`. Maybe It's hard to support all the the types. we can implement reordering of standard collections such as List, Dict, Set ..etc? What do you think?

**Comment by ydylla** [comment]
Yes reordering should be possible. It should happen around [here](https://github.com/yukinarit/pyserde/blob/f5c03243e2b988848162249ce979effdcc5d9e11/serde/de.py#L638) before we pass `union_args` into the template.   

But we need to find a good metric (sort logic). Maybe other dataclasses first then the container types with the most arguments and then primitives will work good enough.

**Comment by yukinarit** [comment]
> But we need to find a good metric (sort logic). Maybe other dataclasses first then the container types with the most arguments and then primitives will work good enough.

Sounds good!

**Comment by yukinarit** [comment]
Tagged union should be used. https://yukinarit.github.io/pyserde/guide/features/union.html
